# Generated by Django 6.0.1 on 2026-01-26 18:55

from django.db import migrations, models


def convert_components_to_dict(apps, schema_editor):
    """Convert components from array format to dict format."""
    Block = apps.get_model('blocks', 'Block')
    for block in Block.objects.all():
        if isinstance(block.components, list):
            # Convert array of objects to dict mapping component_id -> quantity
            components_dict = {}
            for component in block.components:
                if isinstance(component, dict) and 'component_id' in component:
                    components_dict[component['component_id']] = component.get('quantity', 1)
            block.components = components_dict
            block.save()


def reverse_convert(apps, schema_editor):
    """Reverse the conversion (convert dict back to array)."""
    Block = apps.get_model('blocks', 'Block')
    for block in Block.objects.all():
        if isinstance(block.components, dict):
            # Convert dict back to array of objects
            components_array = []
            for comp_id, quantity in block.components.items():
                components_array.append({
                    'component_id': comp_id,
                    'quantity': quantity
                })
            block.components = components_array
            block.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='components',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object mapping component IDs to quantities'),
        ),
        migrations.RunPython(convert_components_to_dict, reverse_convert),
    ]
