# Generated by Django 6.0.1 on 2026-01-19 18:35

import components.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('component_id', models.UUIDField(default=components.models.generate_uuid, editable=False, help_text='Unique identifier for the component', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique Name of the component', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the component')),
                ('materials', models.JSONField(blank=True, default=dict, help_text='JSON field to store material properties associated with the component')),
                ('fabricator_type', models.CharField(blank=True, help_text='Type of fabricator used for the component', max_length=100)),
                ('crafting_time', models.FloatField(default=0.0, help_text='Time required to craft in seconds')),
                ('mass', models.FloatField(default=0.0, help_text='Total mass of the component in kilograms')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the component was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the component was last updated')),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Components',
                'db_table': 'components_component',
                'ordering': ['name'],
            },
        ),
    ]
