# Generated by Django 6.0.1 on 2026-01-20 04:27

import blocks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('block_id', models.UUIDField(default=blocks.models.generate_uuid, editable=False, help_text='UUIDv7 primary key', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Unique name of the block (e.g., 'Large Reactor', 'Small Thruster')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the block and its uses')),
                ('mass', models.FloatField(help_text='Total mass of the block in kilograms')),
                ('components', models.JSONField(blank=True, default=list, help_text='JSON array of component requirements with IDs, names, and quantities')),
                ('health', models.FloatField(help_text='Block health/integrity points')),
                ('pcu', models.IntegerField(help_text='Performance Cost Units (PCU) for this block')),
                ('snap_size', models.FloatField(help_text='Grid snap size for placement')),
                ('input_mass', models.IntegerField(help_text='Input mass capacity in kg')),
                ('output_mass', models.IntegerField(help_text='Output mass capacity in kg')),
                ('consumer_type', models.CharField(blank=True, help_text="Type of resource consumed (e.g., 'Power', 'Hydrogen', 'Oxygen')", max_length=50)),
                ('consumer_rate', models.FloatField(default=0.0, help_text='Consumption rate per second')),
                ('producer_type', models.CharField(blank=True, help_text="Type of resource produced (e.g., 'Power', 'Hydrogen', 'Oxygen')", max_length=50)),
                ('producer_rate', models.FloatField(default=0.0, help_text='Production rate per second')),
                ('storage_capacity', models.FloatField(default=0.0, help_text='Storage capacity in liters or units')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the block was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the block was last updated')),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
                'db_table': 'blocks_block',
                'ordering': ['name'],
            },
        ),
    ]
