# Generated by Django 6.0.1 on 2026-02-02 05:16

import buildorders.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuildOrder",
            fields=[
                (
                    "order_id",
                    models.UUIDField(
                        default=buildorders.models.generate_uuid,
                        editable=False,
                        help_text="UUIDv7 primary key",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the build order", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                (
                    "blocks",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON object mapping block IDs to quantities",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Build Order",
                "verbose_name_plural": "Build Orders",
                "db_table": "buildorders_buildorder",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="buildorders_name_5e2939_idx"),
                    models.Index(
                        fields=["-created_at"], name="buildorders_created_c708df_idx"
                    ),
                ],
            },
        ),
    ]
